FROM alfresco/alfresco-share:7.2.0

ADD share-config-custom.xml /usr/local/tomcat/shared/classes/alfresco/web-extension/
ADD share-config.xml /usr/local/tomcat/webapps/share/WEB-INF/classes/alfresco/ 
