FROM alfresco/alfresco-content-repository-community:7.2.0

ADD mariadb-java-client-2.2.5.jar /usr/local/tomcat/lib/
ADD modelFhc.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD model-papiro.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD digitalArchiveModel.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD fh-scripts-context.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD custom-model-context.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD digitalArchive-context.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD ephesoftModel.xml /usr/local/tomcat/shared/classes/alfresco/extension/
ADD alfresco-remote-api-14.145.jar /usr/local/tomcat/webapps/alfresco/WEB-INF/lib/
